CREATE TABLE Clients( 
ClientId INT PRIMARY KEY IDENTITY,
FirstName VARCHAR(50) NOT NULL,
LastName VARCHAR(50) NOT NULL,
Phone VARCHAR(12) NOT NULL CHECK(LEN(Phone) = 12)
)

CREATE TABLE Mechanics(
MechanicId INT PRIMARY KEY IDENTITY,
FirstName VARCHAR(50) NOT NULL,
LastName VARCHAR(50) NOT NULL,
[Address] VARCHAR(255) NOT NULL
)

CREATE TABLE Models( 
ModelId INT PRIMARY KEY IDENTITY,
[Name] VARCHAR(50) UNIQUE NOT NULL
)

CREATE TABLE Vendors(
VendorId INT PRIMARY KEY IDENTITY,
[Name] VARCHAR(50) UNIQUE NOT NULL
)

CREATE TABLE Parts(
PartId INT PRIMARY KEY IDENTITY,
SerialNumber VARCHAR(50) UNIQUE NOT NULL,
[Description] VARCHAR(255),
Price DECIMAL(15, 2) NOT NULL CHECK(Price > 0),
VendorId INT NOT NULL FOREIGN KEY(VendorId) REFERENCES Vendors(VendorId),
StockQty INT NOT NULL CHECK(StockQty >= 0) DEFAULT 0
)

CREATE TABLE Jobs(
JobId INT PRIMARY KEY IDENTITY,
ModelId INT NOT NULL FOREIGN KEY(ModelId) REFERENCES Models(ModelId),
[Status] VARCHAR(11) NOT NULL 
         CHECK([Status] = 'Pending' OR [Status] = 'In Progress' 
		                  OR [Status] = 'Finished')
		 DEFAULT 'Pending',
ClientId INT NOT NULL FOREIGN KEY(ClientId) REFERENCES Clients(ClientId),
MechanicId INT FOREIGN KEY(MechanicId) REFERENCES Mechanics(MechanicId),
IssueDate DATE NOT NULL,
FinishDate DATE
)

CREATE TABLE Orders(
OrderId INT PRIMARY KEY IDENTITY,
JobId INT NOT NULL FOREIGN KEY(JobId) REFERENCES Jobs(JobId),
IssueDate DATE,
Delivered BIT NOT NULL DEFAULT 0
)

CREATE TABLE OrderParts(
OrderId INT NOT NULL
FOREIGN KEY(OrderId) REFERENCES Orders(OrderId),

PartId INT NOT NULL
FOREIGN KEY(PartId) REFERENCES Parts(PartId),

Quantity INT NOT NULL CHECK(Quantity > 0) DEFAULT 1,

CONSTRAINT PK_OrderParts PRIMARY KEY(OrderId, PartId)
)

CREATE TABLE PartsNeeded(
JobId INT NOT NULL FOREIGN KEY(JobId) REFERENCES Jobs(JobId),
PartId INT NOT NULL FOREIGN KEY(PartId) REFERENCES Parts(PartId),
Quantity INT NULL CHECK(Quantity > 0) DEFAULT 1,

CONSTRAINT PK_PartsNeeded PRIMARY KEY(JobId, PartId)
)

