CREATE TABLE Cities(
	CityID INT NOT NULL,
	[Name] VARCHAR(50) NOT NULL
)

CREATE TABLE Customers(
	CustomerID INT NOT NULL,
	[Name] VARCHAR(50) NOT NULL,
	Birthday DATE NOT NULL,
	CityId INT NOT NULL
)

CREATE TABLE Orders(
	OrderID INT NOT NULL,
	CustomerID INT NOT NULL
)

CREATE TABLE ItemTypes(
	ItemTypeID INT NOT NULL,
	[Name] VARCHAR(50) NOT NULL
)

CREATE TABLE Items(
	ItemID INT NOT NULL,
	[Name] VARCHAR(50) NOT NULL,
	ItemTypeID INT NOT NULL
)

CREATE TABLE OrderItems(
	OrderID INT NOT NULL,
	ItemID INT NOT NULL
)

ALTER TABLE Cities
ADD CONSTRAINT PK_Cities PRIMARY KEY (CityID),
	CONSTRAINT CHK_CityName CHECK (LEN([Name]) > 2)

ALTER TABLE Customers
ADD CONSTRAINT PK_Customers PRIMARY KEY(CustomerID),
	CONSTRAINT CHK_CustomerName CHECK (LEN([Name]) > 2),
	CONSTRAINT FK_Customers_Cities FOREIGN KEY (CityID) REFERENCES Cities(CityID)

ALTER TABLE Orders
ADD CONSTRAINT PK_Orders PRIMARY KEY(OrderID),
	CONSTRAINT FK_Orders_Customers FOREIGN KEY (CustomerID) 
	REFERENCES Customers(CustomerID)

ALTER TABLE ItemTypes
ADD CONSTRAINT PK_ItemTypes PRIMARY KEY(ItemTypeID),
CONSTRAINT CHK_ItemTypeName CHECK (LEN([Name]) > 2)

ALTER TABLE Items
ADD CONSTRAINT PK_Items PRIMARY KEY(ItemID),
	CONSTRAINT CHK_ItemName CHECK (LEN([Name]) > 2),
	CONSTRAINT FK_Item_ItemTypes FOREIGN KEY (ItemTypeID)
	REFERENCES ItemTypes(ItemTypeID)

ALTER TABLE OrderItems
ADD CONSTRAINT FK_OrderItems_Orders FOREIGN KEY(OrderID)
    REFERENCES Orders(OrderID),
	CONSTRAINT FK_OrderItems_Items FOREIGN KEY(ItemID)
    REFERENCES Items(ItemID),
	CONSTRAINT PK_OrderItems PRIMARY KEY (OrderID, ItemID)